### ISSUE TITLE
Cannot find 'lib.d.ts'

### ISSUE THREAD

**Issue by Thomasp24** [nwolverson/blog-typescript-api#1]
Hey I tried your in-memory CompilerHost. Seems promising! However, for even compilation I do, I get the follow result when ```console.log```-ing emitDiagnostics:
```
File '/Users/thomasp/Desktop/thomasp/node_modules/typescript/lib/lib.d.ts' not found.
Cannot find global type 'Array'.
Cannot find global type 'Boolean'.
Cannot find global type 'Function'.
Cannot find global type 'IArguments'.
Cannot find global type 'Number'.
Cannot find global type 'Object'.
Cannot find global type 'RegExp'.
Cannot find global type 'String'.
```

I tried changing ```getDefaultLibFileName = (options: ts.CompilerOptions) => 'lib.d.ts';``` to the full path of the file, but it doesn't work. 
I made a repo to demonstrate: https://github.com/Thomasp24/Typescript-Compiler-Test 

Do you have any idea how to resolve this?

**Comment by nwolverson** [comment]
Have a look here

https://github.com/nwolverson/tstooltip/blob/master/worker/worker.ts#L55

I basically used the same thing and loaded the `lib.d.ts` initially (if I wrote this now I'd load it via a bundler instead of directly xhr).

Otherwise depending what you're doing you may wish to turn the lib check off or whatever the option is.

(Obviously the problem with an in-memory host is you need to get the lib file into memory to use it...)

**Comment by Thomasp24** [comment]
Thanks for the quick response! 
I didn't have ```lib.d.ts``` in memory. I assumed the compiler would do that for me because of the ```getDefaultLibFileName()``` / ```getDefaultLibFileLocation()``` methods.
So thanks a lot!

I do have 1 more issue though:
It doesn't seem to be able to recognize import statements. When I try to compile the following:
```
import Calculator from "./calculator";
class HelloWorld {
    private calculator: Calculator;
    constructor() {this.calculator = new Calculator();}

    public sayHelloTo(name: string) {
        console.log("Hello " + name);
    }
}
```
I still get the following output:
```Cannot find module './calculator'.```

The file ```calculator.ts``` is in the same folder and gets included in the compilerHost. It looks like this:
```
export default class Calculator {
    constructor() {}
   // more logic down here
}
```

Do you have any idea how I get the CompilerHost to recognize this situation?

**Comment by Thomasp24** [comment]
Btw, initial question is answered! Thanks a lot for that!
Closing issue.

**Comment by nwolverson** [comment]
If you have files in a folder actually on disk you may want to look into using the default compiler host, I think there's some helper that returns one.

**Comment by Thomasp24** [comment]
The thing is, I already have the file in memory. I don't want to read/write from/to disk in my proces, because I will be changing the files a lot. That would take too long.

**Comment by nwolverson** [comment]
@Thomasp24 sure, then in that case loading all the files into the `CompilerHost` would seem to be the right thing, I'm not sure how path resolution works but need to get the right paths, I guess.

You might want to look at the `LanguageService` API if it's more appropriate to your use case, being designed for editors etc which will make lots of updates to existing set of files.

**Comment by Thomasp24** [comment]
Just an update, I changed all the file paths to their absolute path. 
so: ```"./calculator.ts"``` get changed to ```"Users/thomasp/Desktop/projectfolder/calculator.ts"``` before being added to the CompilerHost by calling ```this.compilerHost.addFile()```. 
I geuss import statements do this automatically.
This seemed to have fixed the issue.
